apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-operator
spec:
  project: operators
  source:
    chart: gitlab-operator
    repoURL: https://charts.gitlab.io
    targetRevision: 2.*.*
    helm:
      releaseName: gitlab-operator
      valuesObject:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
