---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls
spec:
  secretName: homepage-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - homepage.infra.home.arpa
