---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiali-tls
spec:
  secretName: kiali-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - kiali.infra.home.arpa