apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-tls
spec:
  secretName: loki-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - loki.infra.home.arpa
