apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mattermost-tls
  namespace: istio-system
spec:
  secretName: mattermost-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - mattermost.infra.home.arpa
