apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
spec:
  secretName: prometheus-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.infra.home.arpa
