apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox-exporter
spec:
  project: observability
  source:
    chart: prometheus-blackbox-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.*.*
    helm:
      releaseName: prometheus-blackbox-exporter
      valuesObject:
        config:
          modules:
            http_2xx:
              prober: http
              timeout: 5s
              http:
                valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
                valid_status_codes: [200, 204, 301, 302]
                method: GET
                follow_redirects: true
                fail_if_ssl: false
                fail_if_not_ssl: false
                tls_config:
                  insecure_skip_verify: true # for now
                preferred_ip_protocol: "ip4"
                ip_protocol_fallback: false
            http_auth:
              prober: http
              timeout: 5s
              http:
                method: GET
                valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
                valid_status_codes: [401, 403]
                fail_if_ssl: false
                fail_if_not_ssl: false
                tls_config:
                  insecure_skip_verify: true # for now
                preferred_ip_protocol: "ip4"
                ip_protocol_fallback: false
            http_post_2xx:
              prober: http
              timeout: 5s
              http:
                method: POST
                headers:
                  Content-Type: application/json
                body: "{}"
            http_basic_auth_example:
              prober: http
              timeout: 5s
              http:
                method: POST
                headers:
                  Content-Type: application/json
                basic_auth:
                  username: "username"
                  password: "mysecret"
            tls_connect:
              prober: tcp
              timeout: 5s
              tcp:
                tls: true
            icmp_example:
              prober: icmp
              timeout: 5s
              icmp:
                preferred_ip_protocol: "ip4"
                source_ip_address: "127.0.0.1"
            dns_udp_example:
              prober: dns
              timeout: 5s
              dns:
                query_name: "home.arpa"
                query_type: "A"
                valid_rcodes:
                  - NOERROR
                validate_answer_rrs:
                  fail_if_matches_regexp:
                    - ".*127.0.0.1"
                  fail_if_all_match_regexp:
                    - ".*127.0.0.1"
                  fail_if_not_matches_regexp:
                    - "home.arpa\t300\tIN\tA\t10.10.10.1"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
