---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-tls
spec:
  secretName: jaeger-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - jaeger.infra.home.arpa