apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-tls
spec:
  secretName: monitoring-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - obs.infra.home.arpa
    - alert.infra.home.arpa
