apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: istio
spec:  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - istio-system
  sourceRepos:
    - '*'
  destinations:
    - namespace: istio-system
      server: 'https://kubernetes.default.svc'