apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
spec:  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - observability
  sourceRepos:
    - '*'
  destinations:
    - namespace: observability
      server: 'https://kubernetes.default.svc'
