apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    # Chore: Update the chart version
    # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/master/CHART_VERSIONS?ref_type=heads
    version: "9.0.1"
    values:
      certmanager:
        install: false
        installCRDs: false
      certmanager-issuer:
        email: kajeepan.kandeepan@gmail.com
      gitlab-runner:
        install: false
      gitlab:
        gitaly:
          persistence:
            enabled: true
            size: 50Gi
            storageClass: openebs-hostpath
        gitlab-shell:
          sshDaemon: gitlab-sshd
          config:
            proxyProtocol: true
            proxyPolicy: "use"
          istio:
            entryPoint: ssh
        kas:
          ingress:
            enabled: true
            class: istio
            tls:
              enabled: true
              secretName: gitlab-tls
        toolbox:
          backups:
            cron:
              enabled: true
              schedule: "0 2 * * *"
              persistence:
                enabled: true
                accessMode: ReadWriteOnce
                size: 10Gi
              extraArgs: --skip db --skip artifacts
            objectStorage:
              backend: s3
              config:
                # Configure using s3cmd
                secret: gitlab-backups-minio-creds
                key: config
          persistence:
            enabled: true
            size: "10Gi"
            accessMode: ReadWriteOnce
            storageClass: openebs-hostpath
        webservice:
          monitoring:
            ipWhitelist:
              # Kubernetes Cluster IP Range
              - 127.0.0.0/8
              - 10.0.0.0/8
      global:
        appConfig:
          usernameChangingEnabled: false
          object_store:
            enabled: true
            connection:
              secret: gitlab-minio-connection
              key: connection.yml
          artifacts:
            enabled: true
          backups:
            bucket: gitlab-backups
            tmpBucket: gitlab-backups-tmp
          externalDiffs:
            enabled: true
          uploads:
            enabled: true
          lfs:
            enabled: true
          packages:
            enabled: true
          terraformState:
            enabled: true
          ciSecureFiles:
            enabled: true
          dependencyProxy:
            enabled: true
          omniauth:
            enabled: true
            autoSignInWithProvider: openid_connect
            allowSingleSignOn:
              - openid_connect
            blockAutoCreatedUsers: true
            providers:
              - secret: gitlab-keycloak-omniauth
                key: omniauth.yml
        certificates:
          customCAs:
            - secret: homelab-ca
              keys:
                - gitlab.infra.home.arpa.crt
        edition: ee
        gitaly:
          enabled: true
        psql:
          serviceName: gitlab-postgres-rw
          port: 5432
          database: app
          username: app
          password:
            useSecret: true
            secret: gitlab-postgresql-app
            key: password
        hosts:
          domain: infra.home.arpa
          externalIP: 10.10.10.11
          gitlab: {}
          hostSuffix: null
          https: true
          kas: {}
          minio: {}
          pages: {}
          registry: {}
          smartcard: {}
          ssh: ~
          tls: {}
        ingress:
          class: istio
          configureCertmanager: false
          enabled: true
          path: /
          pathType: Prefix
          tls:
            enabled: true
            secretName: gitlab-tls
        kas:
          enabled: true
        minio:
          enabled: false
        monitoring:
          enabled: true
        spamcheck:
          enabled: true
        shell:
          port: 2222
        pages:
          enabled: true
          objectStore:
            enabled: true
            bucket: gitlab-pages
            connection:
              secret: gitlab-minio-connection
              key: connection.yml
        registry:
          enabled: true
        time_zone: Europe/Berlin
      traefik:
        install: false
      postgresql:
        install: false
      prometheus:
        install: false
      redis:
        install: true
        metrics:
          enabled: true
        global:
          storageClass: openebs-hostpath
      registry:
        storage:
          secret: gitlab-registry-minio-connection
          key: registry.s3.yml
        database:
          enabled: true
          host: gitlab-registry-postgres-rw
          port: 5432
          user: app
          name: app
          password:
            secret: gitlab-registry-postgresql-app
            key: password
          migrations:
            enabled: true
      nginx-ingress:
        enabled: false
