apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: gitlab-registry-postgresql-backup
  namespace: gitlab
spec:
  immediate: true
  backupOwnerReference: self
  cluster:
    name: gitlab-registry-postgresql
  method: barmanObjectStore
  schedule: "0 0 23 * * SUN"