apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-registry-postgresql
  namespace: gitlab
spec:
  instances: 2
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  backup:
    barmanObjectStore:
      destinationPath: s3://backups/gitlab-registry
      endpointURL: https://s3.storage.home.arpa:9000
      endpointCA:
        name: homelab-ca
        key: homelab-ca.crt
      # When recovering from WAL or backup, change this value so that the new WAL
      # is written to a new directory in the bucket.
      serverName: cluster-1
      s3Credentials:
        accessKeyId:
          name: gitlab-postgres-s3-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: gitlab-postgres-s3-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
    retentionPolicy: 7d
  # bootstrap:
  #   recovery:
  #     source: gitlab-postgres
  # externalClusters:
  #   - name: gitlab-postgres
  #     barmanObjectStore:
  #       destinationPath: s3://backups/gitlab
  #       endpointURL: https://s3.storage.home.arpa:9000
  #       endpointCA:
  #         name: homelab-ca
  #         key: homelab-ca.crt
  #       # When recovering from WAL or backup, change the value of
  #       # backup.barmanObjectStore.serverName so that the new WAL is written
  #       # to a new directory in the bucket.
  #       serverName: cluster-1
  #       s3Credentials:
  #         accessKeyId:
  #           name: gitlab-postgres-s3-credentials
  #           key: ACCESS_KEY_ID
  #         secretAccessKey:
  #           name: gitlab-postgres-s3-credentials
  #           key: ACCESS_SECRET_KEY
  #       wal:
  #         maxParallel: 8