apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - ./resources/virtualservice.yaml
  - ./resources/gateway.yaml
  - ./resources/postgresql.yaml
  - ./resources/scheduled-backup.yaml
  - ./resources/keycloak.yaml
