apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
spec:
  project: default
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.*.*
    helm:
      releaseName: istio-base
      valueFiles:
        - values/istio-base.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
