apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.*.*
    helm:
      releaseName: cert-manager
      valueFiles:
        - ../values/cert-manager.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy: {}
