apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators
spec:  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
