apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: mattermost-postgres-backup
spec:
  immediate: true
  backupOwnerReference: self
  cluster:
    name: mattermost-postgres
  method: barmanObjectStore
  schedule: "0 0 23 * * SUN"