apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ./resources/dashboards
  - ./resources/kiali
  - ./resources/jaeger
  - ./resources/loki
  - ./resources/otel
  - ./resources/prometheus
  - ./resources/kube-prometheus-stack.yaml
  - ./resources/prometheus-blackbox-exporter.yaml
  - ./resources/metrics-server.yaml
