apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  allInOne:
    options:
      log-level: debug
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: true
    ingressClassName: istio
    hosts:
      - jaeger.infra.home.arpa
    tls:
      - secretName: jaeger-tls
        hosts:
          - jaeger.infra.home.arpa
