apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: observability
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.*.*
    helm:
      releaseName: metrics-server
      valuesObject:
        args:
          - --kubelet-insecure-tls
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
