---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-role
rules:
  - apiGroups:
      - "events.k8s.io"
    resources:
      - "events"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apps"
    resources:
      - "replicasets"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "extensions"
    resources:
      - "replicasets"
    verbs:
      - "get"
      - "list"
      - "watch"
