apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  project: operators
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.*.*
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
