apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: cnpg-operator
spec:
  project: operators
  source:
    chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: '0.*.*'
    helm:
      releaseName: cnpg-operator
      valuesObject:
        replicaCount: 2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
