apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: observability
spec:
  project: observability
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.*.*
    helm:
      releaseName: opentelemetry-operator
      valuesObject:
        manager:
          collectorImage:
            repository: otel/opentelemetry-collector-k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opentelemetry-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
