apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mattermost

resources:
  - resources/gateway.yaml
  - resources/virtualservice.yaml
  - resources/persistent-volume-claim.yaml
  - resources/postgresql.yaml
  - resources/scheduled-backup.yaml
  - resources/mattermost.yaml
