apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  source:
    repoURL: "https://github.com/Kallepan/homelab-kubernetes.git"
    targetRevision: main
    path: apps/cert-manager/deploy/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
