apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: "https://github.com/Kallepan/homelab-kubernetes.git"
    targetRevision: main
    path: apps/gitlab/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
