apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: cni
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.*.*
    helm:
      releaseName: istio-cni
      valuesObject:
        defaultRevision: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
