apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: "https://github.com/Kallepan/homelab-kubernetes.git"
    targetRevision: main
    path: apps/olm/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: olm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
