apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.*.*
    helm:
      releaseName: openebs
      valuesObject:
        engines:
          local:
            lvm:
              enabled: false
            zfs:
              enabled: false
          replicated:
            mayastor:
              enabled: false
        localpv-provisioner:
          localpv:
            basePath: /var/mnt/storage/localpv-hostpath
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
