apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.*.*
    helm:
      releaseName: vault
      valuesObject:
        global:
          enabled: true
          tlsDisable: true
          serverTelemetry:
            prometheusOperator: true
        injector:
          webhook:
            failurePolicy: Fail
          metrics:
            enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
        server:
          logLevel: info
          standalone:
            config: |-
              ui = true

              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                # Enable unauthenticated metrics access (necessary for Prometheus Operator)
                telemetry {
                  unauthenticated_metrics_access = "true"
                }
              }
              storage "file" {
                path = "/vault/data"
              }
              telemetry {
                prometheus_retention_time = "30s"
                disable_hostname = true
              }
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ingress:
            enabled: true
            ingressClassName: istio
            hosts:
              - host: vault.infra.home.arpa
                paths: []
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.infra.home.arpa
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: openebs-hostpath
            accessMode: ReadWriteOnce
        serverTelemetry:
          serviceMonitor:
            enabled: false
            selectors:
              release: kube-prometheus-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
